apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo-app.fullname" . }}-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  # Application configuration
  FRONTEND_CONFIG: |
    {
      "apiEndpoint": "http://{{ include "todo-app.fullname" . }}-backend-svc:{{ .Values.service.backendPort }}",
      "environment": "{{ .Release.Environment }}"
    }
  BACKEND_CONFIG: |
    {
      "environment": "{{ .Release.Environment }}"
    }